[package]
name = "gtmos_kernel"
version = "0.1.0"
edition = "2021"

[lib]
name = "gtmos_kernel"
path = "src/lib.rs"

[dependencies]
font8x8 = { version="0.3.1", default-features=false, features=["unicode"] }
spin = "0.9.2"
lazy_static = { version="1.0", features=["spin_no_std"] }
