[package]
name = "gtmos_tools"
version = "0.1.0"
edition = "2021"
default-run = "qemu-bios"

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.0"

[build-dependencies]
gtmos_kernel = { path = "../kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "0.11.4"
